import { buildTfvRequest,hashTfvPayload,type TfvProfileSelection } from "./submission-payload";
import { TwilioServiceError } from "@/services/twilio";
import type { TfvSubmitDependencies,TfvSubmitResult } from "./types";
export class TfvSubmitEngine{
 constructor(private readonly d:TfvSubmitDependencies){}
 async execute(input:{applicationId:string;actorId:string|null;dryRun:boolean;operatorConfirmed?:boolean;operationId?:string;profile?:TfvProfileSelection}):Promise<TfvSubmitResult>{
  const c=await this.d.repository.getSubmissionCandidate(input.applicationId);if(!c)return result(input.applicationId,"validation_failed",null,["TFV draft was not found."]);if(c.verificationSid)return result(c.id,"duplicate",c.verificationSid,[]);if(["submitting","recovery_required"].includes(c.status))return result(c.id,"recovery_required",null,["A previous submission must be reconciled."]);if(!c.tollfreePhoneNumberSid)return result(c.id,"validation_failed",null,["A valid purchased PN SID is required."]);
  const profile=input.profile??{mode:"WITHOUT_PROFILE"};const built=buildTfvRequest({submissionPayloadEn:c.submissionPayloadEn,tollfreePhoneNumberSid:c.tollfreePhoneNumberSid,profile});if(!built.payload)return result(c.id,"validation_failed",null,built.errors);if(input.dryRun)return result(c.id,"dry_run",null,[]);if(!input.operatorConfirmed)return result(c.id,"validation_failed",null,["Operator confirmation is required."]);if(!this.d.executionEnabled)return result(c.id,"validation_failed",null,["TWILIO_EXECUTION_ENABLED is false."]);if(!input.operationId)return result(c.id,"validation_failed",null,["operationId is required."]);
  await this.d.audit.append({clientId:c.clientId,actorId:input.actorId,action:"tfv_prepared",entityType:"tfv_application",entityId:c.id,safeDetails:{operationId:input.operationId}});await this.d.repository.markSubmitting(c.id,hashTfvPayload(built.payload));
  try{const submitted=await this.d.twilio.submitTfv(built.payload);if(!/^HH[A-Za-z0-9]{32}$/.test(submitted.verificationSid))throw new Error("Twilio returned no valid HH SID.");await this.d.repository.markSubmitted({applicationId:c.id,verificationSid:submitted.verificationSid,status:submitted.status,snapshot:built.payload,operationId:input.operationId,sanitizedResponse:{verificationSid:submitted.verificationSid,status:submitted.status}});await this.d.audit.append({clientId:c.clientId,actorId:input.actorId,action:"tfv_submitted",entityType:"tfv_application",entityId:c.id,safeDetails:{operationId:input.operationId,verificationSid:submitted.verificationSid,status:submitted.status}});return result(c.id,"submitted",submitted.verificationSid,[]);}catch(error){const definitive=error instanceof TwilioServiceError&&error.httpStatus!==null&&error.httpStatus>=400&&error.httpStatus<500;if(definitive){const message="Twilio rejected the TFV request.";await this.d.repository.markSubmissionFailed(c.id,message);await this.d.audit.append({clientId:c.clientId,actorId:input.actorId,action:"tfv_failed",entityType:"tfv_application",entityId:c.id,safeDetails:{operationId:input.operationId,errorCode:error.twilioErrorCode}});return result(c.id,"failed",null,[message]);}const message="TFV submission outcome is uncertain and requires reconciliation.";await this.d.repository.markSubmissionRecoveryRequired(c.id,message);await this.d.audit.append({clientId:c.clientId,actorId:input.actorId,action:"tfv_recovery_required",entityType:"tfv_application",entityId:c.id,safeDetails:{operationId:input.operationId}});return result(c.id,"recovery_required",null,[message]);}
 }
 async submitTfv(input:Parameters<TfvSubmitEngine["execute"]>[0]){return this.execute(input);}
 async executeBatch(input:{applicationIds:readonly string[];actorId:string|null;dryRun:boolean;operatorConfirmed?:boolean;operationId:string;profile?:TfvProfileSelection}){const results=[];for(const applicationId of input.applicationIds)results.push(await this.execute({...input,applicationId}));return results;}
}
function result(applicationId:string,status:TfvSubmitResult["status"],verificationSid:string|null,errors:readonly string[]):TfvSubmitResult{return{applicationId,status,verificationSid,errors};}
