import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir } from "node:fs/promises";

const uiFiles=["src/app/find-purchase/page.tsx","src/app/tfv/page.tsx","src/components/tfv/status-sync-button.tsx"];
test("UI actions call authenticated API routes and contain no fake-success mechanisms",async()=>{const source=(await Promise.all(uiFiles.map(file=>readFile(file,"utf8")))).join("\n");for(const route of ["/api/twilio/available-phone-numbers","/api/twilio/purchases","/api/twilio/tfv","/api/twilio/tfv/status"])assert.match(source,new RegExp(route.replaceAll("/","\/")));assert.doesNotMatch(source,/console\.log|setTimeout|Math\.random|mock success|fake success|random status/i);assert.match(source,/window\.confirm/);});
test("Twilio SDK initialization is confined to the client factory",async()=>{const files=await sourceFiles("src");const offenders=[];for(const file of files){const source=await readFile(file,"utf8");if(/from ["']twilio["']/.test(source)&&!file.replaceAll("\\","/").endsWith("src/services/twilio/client-factory.ts")&&!source.includes('import type { Twilio }'))offenders.push(file);}assert.deepEqual(offenders,[]);});
test("production migrations define operation, SID, snapshot, recovery and status persistence",async()=>{const names=(await readdir("supabase/migrations")).sort();const sql=(await Promise.all(names.map(name=>readFile(`supabase/migrations/${name}`,"utf8")))).join("\n");for(const token of ["purchase_operation_id","phone_number_sid","verification_sid","request_snapshot","response_snapshot","recovery_required","error_code","rejection_reason","prepare_tfv_batch","save_import_draft_atomic"])assert.match(sql,new RegExp(token));});
test("Twilio execution flag is not exposed as NEXT_PUBLIC",async()=>{const files=await sourceFiles("src");for(const file of files)assert.doesNotMatch(await readFile(file,"utf8"),/NEXT_PUBLIC_TWILIO/);});
async function sourceFiles(root:string):Promise<string[]>{const entries=await readdir(root,{withFileTypes:true});const output:string[]=[];for(const entry of entries){const path=`${root}/${entry.name}`;if(entry.isDirectory())output.push(...await sourceFiles(path));else if(/\.(ts|tsx)$/.test(entry.name))output.push(path);}return output;}
