/**
 * Canonical field registry for Twilio Toll-Free Verification (TFV).
 *
 * This file is the single source of truth for TFV field names, validation,
 * persistence mappings, and import/export headings. Import, purchase, TFV, and
 * status modules must consume this registry instead of redefining TFV fields.
 */

export enum BusinessType {
  PRIVATE_PROFIT = "PRIVATE_PROFIT",
  PUBLIC_PROFIT = "PUBLIC_PROFIT",
  SOLE_PROPRIETOR = "SOLE_PROPRIETOR",
  NON_PROFIT = "NON_PROFIT",
  GOVERNMENT = "GOVERNMENT",
}

export enum UseCaseCategories {
  TWO_FACTOR_AUTHENTICATION = "TWO_FACTOR_AUTHENTICATION",
  ACCOUNT_NOTIFICATIONS = "ACCOUNT_NOTIFICATIONS",
  CUSTOMER_CARE = "CUSTOMER_CARE",
  CHARITY_NONPROFIT = "CHARITY_NONPROFIT",
  DELIVERY_NOTIFICATIONS = "DELIVERY_NOTIFICATIONS",
  FRAUD_ALERT_MESSAGING = "FRAUD_ALERT_MESSAGING",
  EVENTS = "EVENTS",
  HIGHER_EDUCATION = "HIGHER_EDUCATION",
  K12 = "K12",
  MARKETING = "MARKETING",
  POLLING_AND_VOTING_NON_POLITICAL = "POLLING_AND_VOTING_NON_POLITICAL",
  POLITICAL_ELECTION_CAMPAIGNS = "POLITICAL_ELECTION_CAMPAIGNS",
  PUBLIC_SERVICE_ANNOUNCEMENT = "PUBLIC_SERVICE_ANNOUNCEMENT",
  SECURITY_ALERT = "SECURITY_ALERT",
}

export enum OptInType {
  VERBAL = "VERBAL",
  WEB_FORM = "WEB_FORM",
  PAPER_FORM = "PAPER_FORM",
  VIA_TEXT = "VIA_TEXT",
  MOBILE_QR_CODE = "MOBILE_QR_CODE",
  IMPORT = "IMPORT",
  IMPORT_PLEASE_REPLACE = "IMPORT_PLEASE_REPLACE",
}

export enum MessageVolume {
  TEN = "10",
  ONE_HUNDRED = "100",
  ONE_THOUSAND = "1,000",
  TEN_THOUSAND = "10,000",
  ONE_HUNDRED_THOUSAND = "100,000",
  TWO_HUNDRED_FIFTY_THOUSAND = "250,000",
  FIVE_HUNDRED_THOUSAND = "500,000",
  SEVEN_HUNDRED_FIFTY_THOUSAND = "750,000",
  ONE_MILLION = "1,000,000",
  FIVE_MILLION = "5,000,000",
  TEN_MILLION_PLUS = "10,000,000+",
}

export enum BusinessRegistrationAuthority {
  EIN = "EIN",
  CBN = "CBN",
  CRN = "CRN",
  PROVINCIAL_NUMBER = "PROVINCIAL_NUMBER",
  VAT = "VAT",
  ACN = "ACN",
  ABN = "ABN",
  BRN = "BRN",
  SIREN = "SIREN",
  SIRET = "SIRET",
  NZBN = "NZBN",
  UST_ID_NR = "USt-IdNr",
  CIF = "CIF",
  NIF = "NIF",
  CNPJ = "CNPJ",
  UID = "UID",
  NEQ = "NEQ",
  OTHER = "OTHER",
}

export enum VettingProvider {
  CAMPAIGN_VERIFY = "CAMPAIGN_VERIFY",
}

export type TfvFieldType =
  | "string"
  | "email"
  | "url"
  | "phone"
  | "boolean"
  | "integer"
  | "dateTime"
  | "sid"
  | "enum"
  | "stringArray"
  | "enumArray"
  | "object"
  | "objectArray";

export type TfvFieldOperation = "create" | "update" | "response";

export interface TfvFieldDefinition {
  readonly fieldName: string;
  readonly apiName: string;
  readonly label: string;
  readonly description: string;
  readonly type: TfvFieldType;
  readonly requiredByTwilio: boolean;
  readonly requiredByBusiness: boolean;
  readonly nullable: boolean;
  readonly enumValues: readonly string[];
  readonly validationRule: string;
  readonly databaseColumn: string | null;
  readonly importColumn: string | null;
  readonly exportColumn: string;
  readonly operations: readonly TfvFieldOperation[];
}

const EMPTY_ENUM = [] as const;
const BUSINESS_TYPES = Object.values(BusinessType);
const USE_CASE_CATEGORIES = Object.values(UseCaseCategories);
const OPT_IN_TYPES = Object.values(OptInType);
const MESSAGE_VOLUMES = Object.values(MessageVolume);
const REGISTRATION_AUTHORITIES = Object.values(BusinessRegistrationAuthority);
const VETTING_PROVIDERS = Object.values(VettingProvider);
const TFV_STATUSES = [
  "PENDING_REVIEW",
  "IN_REVIEW",
  "TWILIO_APPROVED",
  "TWILIO_REJECTED",
] as const;

const field = <const T extends TfvFieldDefinition>(definition: T): T =>
  Object.freeze(definition);

export const TFV_SCHEMA = [
  field({
    fieldName: "sid",
    apiName: "sid",
    label: "Verification SID",
    description: "Unique Twilio identifier for the Toll-Free Verification.",
    type: "sid",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "twilioSid:HA",
    databaseColumn: "verification_sid",
    importColumn: null,
    exportColumn: "verification_sid",
    operations: ["response"],
  }),
  field({
    fieldName: "accountSid",
    apiName: "accountSid",
    label: "Account SID",
    description: "SID of the Twilio Account that created the verification.",
    type: "sid",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "twilioSid:AC",
    databaseColumn: "submission_snapshot.account_sid",
    importColumn: "twilio_account_sid",
    exportColumn: "account_sid",
    operations: ["response"],
  }),
  field({
    fieldName: "customerProfileSid",
    apiName: "customerProfileSid",
    label: "Customer Profile SID",
    description: "SID of the customer's Trust Hub Profile Bundle.",
    type: "sid",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|twilioSid:BU",
    databaseColumn: "application_payload.customer_profile_sid",
    importColumn: null,
    exportColumn: "customer_profile_sid",
    operations: ["create", "response"],
  }),
  field({
    fieldName: "trustProductSid",
    apiName: "trustProductSid",
    label: "Trust Product SID",
    description: "SID of the Toll-Free Trust Product Bundle.",
    type: "sid",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|twilioSid:BU",
    databaseColumn: "submission_snapshot.trust_product_sid",
    importColumn: null,
    exportColumn: "trust_product_sid",
    operations: ["response"],
  }),
  field({
    fieldName: "dateCreated",
    apiName: "dateCreated",
    label: "Date Created",
    description: "GMT date and time when Twilio created the verification.",
    type: "dateTime",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "iso8601",
    databaseColumn: "created_at",
    importColumn: null,
    exportColumn: "date_created",
    operations: ["response"],
  }),
  field({
    fieldName: "dateUpdated",
    apiName: "dateUpdated",
    label: "Date Updated",
    description: "GMT date and time when Twilio last updated the verification.",
    type: "dateTime",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "iso8601",
    databaseColumn: "updated_at",
    importColumn: null,
    exportColumn: "date_updated",
    operations: ["response"],
  }),
  field({
    fieldName: "regulatedItemSid",
    apiName: "regulatedItemSid",
    label: "Regulated Item SID",
    description: "SID of the regulated item associated with the verification.",
    type: "sid",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|twilioSid:RA",
    databaseColumn: "submission_snapshot.regulated_item_sid",
    importColumn: null,
    exportColumn: "regulated_item_sid",
    operations: ["response"],
  }),
  field({
    fieldName: "businessName",
    apiName: "businessName",
    label: "Business Name",
    description: "Legal name of the business or organization using the toll-free number.",
    type: "string",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|string|minLength:1",
    databaseColumn: "application_payload.business_name",
    importColumn: "legal_business_name",
    exportColumn: "business_name",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessStreetAddress",
    apiName: "businessStreetAddress",
    label: "Business Street Address",
    description: "Primary street address of the business or organization.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.business_street_address",
    importColumn: "business_address",
    exportColumn: "business_street_address",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessStreetAddress2",
    apiName: "businessStreetAddress2",
    label: "Business Street Address 2",
    description: "Secondary address line for the business or organization.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string",
    databaseColumn: "application_payload.business_street_address_2",
    importColumn: null,
    exportColumn: "business_street_address_2",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessCity",
    apiName: "businessCity",
    label: "Business City",
    description: "City of the business or organization.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.business_city",
    importColumn: "business_city",
    exportColumn: "business_city",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessStateProvinceRegion",
    apiName: "businessStateProvinceRegion",
    label: "Business State / Province / Region",
    description: "State, province, or region of the business or organization.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.business_state_province_region",
    importColumn: "business_state",
    exportColumn: "business_state_province_region",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessPostalCode",
    apiName: "businessPostalCode",
    label: "Business Postal Code",
    description: "Postal code of the business or organization.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.business_postal_code",
    importColumn: "business_postal_code",
    exportColumn: "business_postal_code",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessCountry",
    apiName: "businessCountry",
    label: "Business Country",
    description: "Country of the business or organization.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|isoCountryCode",
    databaseColumn: "application_payload.business_country",
    importColumn: "business_country",
    exportColumn: "business_country",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessWebsite",
    apiName: "businessWebsite",
    label: "Business Website",
    description: "Public website of the business or organization.",
    type: "url",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|url:http,https",
    databaseColumn: "application_payload.business_website",
    importColumn: "business_website",
    exportColumn: "business_website",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessContactFirstName",
    apiName: "businessContactFirstName",
    label: "Business Contact First Name",
    description: "First name of the business contact.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.business_contact_first_name",
    importColumn: null,
    exportColumn: "business_contact_first_name",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessContactLastName",
    apiName: "businessContactLastName",
    label: "Business Contact Last Name",
    description: "Last name of the business contact.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.business_contact_last_name",
    importColumn: null,
    exportColumn: "business_contact_last_name",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessContactEmail",
    apiName: "businessContactEmail",
    label: "Business Contact Email",
    description: "Email address of the business contact.",
    type: "email",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|email",
    databaseColumn: "application_payload.business_contact_email",
    importColumn: "authorized_contact_email",
    exportColumn: "business_contact_email",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessContactPhone",
    apiName: "businessContactPhone",
    label: "Business Contact Phone",
    description: "E.164 phone number of the business contact.",
    type: "phone",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|e164",
    databaseColumn: "application_payload.business_contact_phone",
    importColumn: "authorized_contact_phone",
    exportColumn: "business_contact_phone",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "notificationEmail",
    apiName: "notificationEmail",
    label: "Notification Email",
    description: "Email address that receives the verification result.",
    type: "email",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|email",
    databaseColumn: "application_payload.notification_email",
    importColumn: "notification_email",
    exportColumn: "notification_email",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "useCaseCategories",
    apiName: "useCaseCategories",
    label: "Use Case Categories",
    description: "One or more Twilio categories describing the messaging use case.",
    type: "enumArray",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: USE_CASE_CATEGORIES,
    validationRule: "required|array|minItems:1|unique|enum:UseCaseCategories",
    databaseColumn: "application_payload.use_case_categories",
    importColumn: "use_case_categories",
    exportColumn: "use_case_categories",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "useCaseSummary",
    apiName: "useCaseSummary",
    label: "Use Case Summary",
    description: "Detailed explanation of how the organization uses messaging.",
    type: "string",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|string|minLength:1",
    databaseColumn: "application_payload.use_case_summary",
    importColumn: "message_use_case",
    exportColumn: "use_case_summary",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "productionMessageSample",
    apiName: "productionMessageSample",
    label: "Production Message Sample",
    description: "Representative message content that will be sent in production.",
    type: "string",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|string|minLength:1",
    databaseColumn: "application_payload.production_message_sample",
    importColumn: "sample_messages",
    exportColumn: "production_message_sample",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "optInImageUrls",
    apiName: "optInImageUrls",
    label: "Opt-In Image URLs",
    description: "Publicly hosted image URLs demonstrating the complete opt-in workflow.",
    type: "stringArray",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|array|minItems:1|items:url:http,https",
    databaseColumn: "application_payload.opt_in_image_urls",
    importColumn: "opt_in_image_url",
    exportColumn: "opt_in_image_urls",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "optInType",
    apiName: "optInType",
    label: "Opt-In Type",
    description: "Method by which recipients consent to receive text messages.",
    type: "enum",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: OPT_IN_TYPES,
    validationRule: "required|enum:OptInType",
    databaseColumn: "application_payload.opt_in_type",
    importColumn: "opt_in_type",
    exportColumn: "opt_in_type",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "messageVolume",
    apiName: "messageVolume",
    label: "Monthly Message Volume",
    description: "Estimated monthly message volume sent from the toll-free number.",
    type: "enum",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: MESSAGE_VOLUMES,
    validationRule: "required|enum:MessageVolume",
    databaseColumn: "application_payload.message_volume",
    importColumn: "estimated_monthly_message_volume",
    exportColumn: "message_volume",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "additionalInformation",
    apiName: "additionalInformation",
    label: "Additional Information",
    description: "Additional context supplied to support verification.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string",
    databaseColumn: "application_payload.additional_information",
    importColumn: "additional_notes",
    exportColumn: "additional_information",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "tollfreePhoneNumberSid",
    apiName: "tollfreePhoneNumberSid",
    label: "Toll-Free Phone Number SID",
    description: "SID of the Twilio toll-free phone number being verified.",
    type: "sid",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "required|twilioSid:PN",
    databaseColumn: "phone_number_sid",
    importColumn: null,
    exportColumn: "tollfree_phone_number_sid",
    operations: ["create", "response"],
  }),
  field({
    fieldName: "tollfreePhoneNumber",
    apiName: "tollfreePhoneNumber",
    label: "Toll-Free Phone Number",
    description: "E.164 toll-free phone number associated with the verification.",
    type: "phone",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "e164",
    databaseColumn: "submission_snapshot.tollfree_phone_number",
    importColumn: "phone_number",
    exportColumn: "tollfree_phone_number",
    operations: ["response"],
  }),
  field({
    fieldName: "status",
    apiName: "status",
    label: "Verification Status",
    description: "Current Twilio compliance status of the verification.",
    type: "enum",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: TFV_STATUSES,
    validationRule: "enum:PENDING_REVIEW,IN_REVIEW,TWILIO_APPROVED,TWILIO_REJECTED",
    databaseColumn: "status",
    importColumn: null,
    exportColumn: "status",
    operations: ["response"],
  }),
  field({
    fieldName: "url",
    apiName: "url",
    label: "Resource URL",
    description: "Absolute URL of the Twilio Toll-Free Verification resource.",
    type: "url",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "url:https",
    databaseColumn: "submission_snapshot.url",
    importColumn: null,
    exportColumn: "resource_url",
    operations: ["response"],
  }),
  field({
    fieldName: "rejectionReason",
    apiName: "rejectionReason",
    label: "Rejection Reason",
    description: "Legacy rejection reason returned for a rejected verification.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string",
    databaseColumn: "rejection_reasons",
    importColumn: null,
    exportColumn: "rejection_reason",
    operations: ["response"],
  }),
  field({
    fieldName: "errorCode",
    apiName: "errorCode",
    label: "Error Code",
    description: "Twilio error code associated with a rejected verification.",
    type: "integer",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|integer|min:0",
    databaseColumn: "error_codes",
    importColumn: null,
    exportColumn: "error_code",
    operations: ["response"],
  }),
  field({
    fieldName: "editExpiration",
    apiName: "editExpiration",
    label: "Edit Expiration",
    description: "Date and time when editing a rejected verification expires.",
    type: "dateTime",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|iso8601",
    databaseColumn: "submission_snapshot.edit_expiration",
    importColumn: null,
    exportColumn: "edit_expiration",
    operations: ["response"],
  }),
  field({
    fieldName: "editAllowed",
    apiName: "editAllowed",
    label: "Edit Allowed",
    description: "Whether Twilio permits the rejected verification to be edited and resubmitted.",
    type: "boolean",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: false,
    enumValues: EMPTY_ENUM,
    validationRule: "boolean",
    databaseColumn: "submission_snapshot.edit_allowed",
    importColumn: null,
    exportColumn: "edit_allowed",
    operations: ["response"],
  }),
  field({
    fieldName: "editReason",
    apiName: "editReason",
    label: "Edit Reason",
    description: "Explanation of why a previously rejected verification is being edited.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "requiredOn:update|string|minLength:1",
    databaseColumn: "application_payload.edit_reason",
    importColumn: null,
    exportColumn: "edit_reason",
    operations: ["update"],
  }),
  field({
    fieldName: "businessRegistrationNumber",
    apiName: "businessRegistrationNumber",
    label: "Business Registration Number",
    description: "Legally recognized business registration number.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "requiredUnless:businessType=SOLE_PROPRIETOR|string",
    databaseColumn: "application_payload.business_registration_number",
    importColumn: "business_registration_number",
    exportColumn: "business_registration_number",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessRegistrationAuthority",
    apiName: "businessRegistrationAuthority",
    label: "Business Registration Authority",
    description: "Organizational authority that issued the business registration.",
    type: "enum",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: REGISTRATION_AUTHORITIES,
    validationRule:
      "requiredUnless:businessType=SOLE_PROPRIETOR|enum:BusinessRegistrationAuthority",
    databaseColumn: "application_payload.business_registration_authority",
    importColumn: "business_registration_authority",
    exportColumn: "business_registration_authority",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessRegistrationCountry",
    apiName: "businessRegistrationCountry",
    label: "Business Registration Country",
    description: "Country where the business is legally registered.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "requiredUnless:businessType=SOLE_PROPRIETOR|isoCountryCode",
    databaseColumn: "application_payload.business_registration_country",
    importColumn: "business_registration_country",
    exportColumn: "business_registration_country",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessType",
    apiName: "businessType",
    label: "Business Type",
    description: "Legal organization type of the business.",
    type: "enum",
    requiredByTwilio: true,
    requiredByBusiness: true,
    nullable: false,
    enumValues: BUSINESS_TYPES,
    validationRule: "required|enum:BusinessType",
    databaseColumn: "application_payload.business_type",
    importColumn: "business_type",
    exportColumn: "business_type",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "businessRegistrationPhoneNumber",
    apiName: "businessRegistrationPhoneNumber",
    label: "Business Registration Phone Number",
    description: "E.164 phone number associated with the registered business.",
    type: "phone",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|e164",
    databaseColumn: "application_payload.business_registration_phone_number",
    importColumn: "business_phone",
    exportColumn: "business_registration_phone_number",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "doingBusinessAs",
    apiName: "doingBusinessAs",
    label: "Doing Business As",
    description: "Trade name, sub-entity, or downstream business name.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string",
    databaseColumn: "application_payload.doing_business_as",
    importColumn: "dba",
    exportColumn: "doing_business_as",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "optInConfirmationMessage",
    apiName: "optInConfirmationMessage",
    label: "Opt-In Confirmation Message",
    description: "Confirmation message sent when a recipient opts in.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.opt_in_confirmation_message",
    importColumn: "opt_in_message",
    exportColumn: "opt_in_confirmation_message",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "helpMessageSample",
    apiName: "helpMessageSample",
    label: "Help Message Sample",
    description: "Sample HELP response provided to message recipients.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string|minLength:1",
    databaseColumn: "application_payload.help_message_sample",
    importColumn: "help_message",
    exportColumn: "help_message_sample",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "privacyPolicyUrl",
    apiName: "privacyPolicyUrl",
    label: "Privacy Policy URL",
    description: "Public URL of the business privacy policy.",
    type: "url",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|url:http,https",
    databaseColumn: "application_payload.privacy_policy_url",
    importColumn: "privacy_policy_url",
    exportColumn: "privacy_policy_url",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "termsAndConditionsUrl",
    apiName: "termsAndConditionsUrl",
    label: "Terms and Conditions URL",
    description: "Public URL of the business terms and conditions.",
    type: "url",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|url:http,https",
    databaseColumn: "application_payload.terms_and_conditions_url",
    importColumn: "terms_and_conditions_url",
    exportColumn: "terms_and_conditions_url",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "ageGatedContent",
    apiName: "ageGatedContent",
    label: "Age-Gated Content",
    description: "Whether the messaging program contains age-gated content.",
    type: "boolean",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|boolean",
    databaseColumn: "application_payload.age_gated_content",
    importColumn: "age_gated_content",
    exportColumn: "age_gated_content",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "optInKeywords",
    apiName: "optInKeywords",
    label: "Opt-In Keywords",
    description: "Keywords recipients can text to opt in or out of messages.",
    type: "stringArray",
    requiredByTwilio: false,
    requiredByBusiness: true,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|array|unique|items:string,minLength:1",
    databaseColumn: "application_payload.opt_in_keywords",
    importColumn: "opt_in_keywords",
    exportColumn: "opt_in_keywords",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "rejectionReasons",
    apiName: "rejectionReasons",
    label: "Rejection Reasons",
    description: "Structured Twilio rejection reasons and codes for a rejected verification.",
    type: "objectArray",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|array|items:object",
    databaseColumn: "rejection_reasons",
    importColumn: null,
    exportColumn: "rejection_reasons",
    operations: ["response"],
  }),
  field({
    fieldName: "resourceLinks",
    apiName: "resourceLinks",
    label: "Resource Links",
    description: "URLs of documents associated with the verification resource.",
    type: "object",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|object",
    databaseColumn: "submission_snapshot.resource_links",
    importColumn: null,
    exportColumn: "resource_links",
    operations: ["response"],
  }),
  field({
    fieldName: "externalReferenceId",
    apiName: "externalReferenceId",
    label: "External Reference ID",
    description: "Customer-supplied reference identifier echoed by Twilio.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|string",
    databaseColumn: "application_payload.external_reference_id",
    importColumn: "external_reference_id",
    exportColumn: "external_reference_id",
    operations: ["create", "response"],
  }),
  field({
    fieldName: "vettingId",
    apiName: "vettingId",
    label: "Vetting ID",
    description: "Unique identifier assigned by the third-party political vetting provider.",
    type: "string",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule:
      "requiredWith:vettingProvider|requiredForUseCase:POLITICAL_ELECTION_CAMPAIGNS|string",
    databaseColumn: "application_payload.vetting_id",
    importColumn: "vetting_id",
    exportColumn: "vetting_id",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "vettingProvider",
    apiName: "vettingProvider",
    label: "Vetting Provider",
    description: "Third-party provider that performed political campaign vetting.",
    type: "enum",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: VETTING_PROVIDERS,
    validationRule:
      "requiredWith:vettingId|requiredForUseCase:POLITICAL_ELECTION_CAMPAIGNS|enum:VettingProvider",
    databaseColumn: "application_payload.vetting_provider",
    importColumn: "vetting_provider",
    exportColumn: "vetting_provider",
    operations: ["create", "update", "response"],
  }),
  field({
    fieldName: "vettingIdExpiration",
    apiName: "vettingIdExpiration",
    label: "Vetting ID Expiration",
    description: "Expiration date and time of the third-party political vetting ID.",
    type: "dateTime",
    requiredByTwilio: false,
    requiredByBusiness: false,
    nullable: true,
    enumValues: EMPTY_ENUM,
    validationRule: "optional|iso8601",
    databaseColumn: "submission_snapshot.vetting_id_expiration",
    importColumn: null,
    exportColumn: "vetting_id_expiration",
    operations: ["response"],
  }),
] as const satisfies readonly TfvFieldDefinition[];

export type TfvFieldName = (typeof TFV_SCHEMA)[number]["fieldName"];
export type TfvCanonicalField = (typeof TFV_SCHEMA)[number];

export const TFV_FIELD_COUNT = TFV_SCHEMA.length;
export const TFV_ENUM_COUNT = 6;

export const TFV_FIELD_BY_NAME = Object.freeze(
  Object.fromEntries(TFV_SCHEMA.map((definition) => [definition.fieldName, definition])),
) as Readonly<Record<TfvFieldName, TfvCanonicalField>>;

export function getTfvField(fieldName: TfvFieldName): TfvCanonicalField {
  return TFV_FIELD_BY_NAME[fieldName];
}
